library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(EnhancedVolcano)
tcf21.data <- Read10X(data.dir = "tcf21")
tcf21 <- CreateSeuratObject(counts = tcf21.data, project = "tcf21", min.cells = 3, min.features = 200)
tcf21=subset(x = tcf21, subset = tcf21 > 0|EGFP > 0)
tcf21[["percent.mt"]] <- PercentageFeatureSet(tcf21, pattern = "^mt-")
tcf21 <- subset(tcf21, subset = nFeature_RNA > 200 & nFeature_RNA < 3000 & percent.mt < 5)
tcf21 <- NormalizeData(tcf21, normalization.method = "LogNormalize", scale.factor = 10000)
tcf21 <- FindVariableFeatures(tcf21, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(tcf21)
tcf21 <- ScaleData(tcf21, features = all.genes)
tcf21 <- RunPCA(tcf21, npcs = 30, verbose = FALSE)
tcf21 <- FindNeighbors(tcf21, dims = 1:15)
tcf21 <- FindClusters(tcf21, resolution = 0.3)
tcf21 <- RunUMAP(tcf21, reduction = "pca", dims = 1:15)
DimPlot(tcf21, reduction = "umap")
tcf21.markers <- FindAllMarkers(tcf21, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(tcf21.markers,file="tcf21markergenes.csv")
top10 <- tcf21.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
DoHeatmap(tcf21, features = top10$gene)
FeaturePlot(tcf21, features = c("hapln1a"),pt.size=1)
VlnPlot(tcf21, features = c("hapln1a"))
ggplot(pathway,aes(Clusters,BiologicalProcess))+geom_point(aes(size=Enrichment,color=-1*log10(LogP)))+scale_color_gradient(low="green",high = "red")+scale_size_continuous(range = c(4, 12))+theme(axis.text.y = element_text(size=12, color="black"))+theme(axis.text.x = element_text(size=12, color="black"))+labs(x = "Clusters", y = "Biological processes")+theme(axis.title.x = element_text(size=15))+theme(axis.title.y = element_text(size=15))
ggplot(go,aes(x=enrichment,y=GO,fill=pvalue))+ geom_bar(stat="identity")+scale_fill_gradientn(colors = c("blue", "white", "red"))
EnhancedVolcano(a,lab = rownames(a),x = 'log2FC', y = 'pvalue',pCutoff = 10e-3,FCcutoff = 0.25,legendPosition = 'right',drawConnectors = TRUE,widthConnectors = 0.75,selectLab = c('angptl1a','ntn1','fn1a','cxcl12a','fstl1b','dcn','mdka','rspo3','vcam1b','fgl2b','loxl2a','tgfb1a'),)+xlim(-2, 2)
