library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
Reg.data <- Read10X(data.dir = "Reg")
Dev.data <- Read10X(data.dir = "Dev")
Reg <- CreateSeuratObject(counts = Reg.data, project = "Reg", min.cells = 3, min.features = 200)
Dev <- CreateSeuratObject(counts = Dev.data, project = "Dev", min.cells = 3, min.features = 200)
Reg=subset(x = Reg, subset = hapln1a > 0|EGFP>0)
Dev=subset(x = Dev, subset = hapln1a > 0|EGFP>0)
Reg[["percent.mt"]] <- PercentageFeatureSet(Reg, pattern = "^mt-")
Dev[["percent.mt"]] <- PercentageFeatureSet(Dev, pattern = "^mt-")
Reg <- subset(Reg, subset = nFeature_RNA > 200 & nFeature_RNA < 3000 & percent.mt < 5)
Dev <- subset(Dev, subset = nFeature_RNA > 200 & nFeature_RNA < 3000 & percent.mt < 5)
Reg <- AddMetaData(Reg, metadata="injured", col.name="Condition")
Dev <- AddMetaData(Dev, metadata="developing", col.name="Condition")
Dev <- NormalizeData(Dev, normalization.method = "LogNormalize", scale.factor = 10000)
Reg <- NormalizeData(Reg, normalization.method = "LogNormalize", scale.factor = 10000)
Reg <- FindVariableFeatures(Reg, selection.method = "vst", nfeatures = 2000)
Dev <- FindVariableFeatures(Dev, selection.method = "vst", nfeatures = 2000)
hapln1a.list <- list(Reg,Dev)
hapln1a.anchors <- FindIntegrationAnchors(object.list = hapln1a.list, dims = 1:30)
hapln1a.integrated <- IntegrateData(anchorset = hapln1a.anchors, dims = 1:30)
DefaultAssay(hapln1a.integrated) <- "integrated"
hapln1a.integrated <- ScaleData(hapln1a.integrated, verbose = FALSE)
hapln1a.integrated <- RunPCA(hapln1a.integrated, npcs = 30, verbose = FALSE)
hapln1a.integrated <- FindNeighbors(hapln1a.integrated, dims = 1:20)
hapln1a.integrated <- FindClusters(hapln1a.integrated, resolution = 0.3)
hapln1a.integrated <- RunUMAP(hapln1a.integrated, reduction = "pca", dims = 1:20)
DimPlot(hapln1a.integrated, reduction = "umap", split.by = "Condition",label = T,pt.size = 1, label.size = 6)
DefaultAssay(hapln1a.integrated) <- "RNA"
FeaturePlot(hapln1a.integrated, features = c("serpine1"),pt.size=1,split.by = "Condition")


